config/routes.rb
Rails.application.routes.draw do

  root 'sessions#new'

  resources :users do
    resources :goals
  end
  resource :session, only: [:create, :new, :destroy]

  resources :comments, only: [:create, :destroy]

end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id               :integer          not null, primary key
#  body             :text             not null
#  user_id          :integer          not null
#  commentable_id   :integer          not null
#  commentable_type :string(255)      not null
#  created_at       :datetime
#  updated_at       :datetime
#

class Comment < ActiveRecord::Base
  validates :body, :user_id, :commentable_id, :commentable_type, presence: true
  validates :commentable_type, inclusion: { in: %w(User Goal) }
  belongs_to :commentable, polymorphic: true
  belongs_to :user

end

app/models/concerns/commentable.rb
require 'active_support/concern'

module Commentable
  extend ActiveSupport::Concern

  included do
    has_many :comments, as: :commentable
  end

end

app/models/goal.rb
# == Schema Information
#
# Table name: goals
#
#  id          :integer          not null, primary key
#  private     :boolean          default(FALSE), not null
#  completed   :boolean          default(FALSE), not null
#  user_id     :integer
#  title       :string(255)      not null
#  description :text
#  created_at  :datetime
#  updated_at  :datetime
#

class Goal < ActiveRecord::Base
  include Commentable
  validates :title, :user, presence: true

  belongs_to :user

  def to_s
    self.title
  end

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  username        :string(255)      not null
#  password_digest :string(255)      not null
#  session_token   :string(255)
#  created_at      :datetime
#  updated_at      :datetime
#

class User < ActiveRecord::Base
  include Commentable

  validates :username, presence: true
  validates :password, presence: true

  has_many :goals

  def to_s
    self.username
  end


  def password
    self.password_digest
  end

  def password=(plain_text)
    if plain_text.empty?
      errors.add(:password, "can't be blank")
    elsif plain_text.length < 6
      errors.add(:password, "is too short")
    else
      self.password_digest = BCrypt::Password.create(plain_text)
    end
  end

  def is_password?(plain_text)
    BCrypt::Password.new(self.password_digest).is_password?(plain_text)
  end

  def reset_session_token
    self.update(session_token: SecureRandom::urlsafe_base64(16))
    self.session_token
  end

  def self.find_by_credentials(user_params)
    user = self.find_by(username: user_params[:username])
    return user if user && user.is_password?(user_params[:password])
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include SessionsHelper

  helper_method :current_user, :logged_in?, :form_auth_html, :update_method_html

  def form_auth_html
    "<input type='hidden' name='authenticity_token' value='#{form_authenticity_token}'>".html_safe
  end

  def update_method_html
    "<input type='hidden' name='_method' value='patch'>".html_safe
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController


  def create
    @comment = Comment.new(comment_params)
    @comment.user = current_user

    unless @comment.save
      flash[:errors] = @comment.errors.full_messages
    end
    if @comment.commentable.class == User
      redirect_to @comment.commentable
    else
      user = @comment.commentable.user
      redirect_to url_for([user, @comment.commentable])
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    object = @comment.commentable
    @comment.delete
    if object.class == User
      redirect_to object
    else
      user = object.user
      redirect_to url_for([user, object])
    end
  end


  private

  def comment_params
    params.require(:comment)
    .permit(:body, :commentable_id, :commentable_type)
  end

end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController

  before_action :set_user # except for the current user's goal index
  before_action :set_goal, only: [:edit, :update, :show, :destroy]

  def new
    @goal = Goal.new
  end

  def index
    @goals = @user.goals
    @uncompleted = @goals.reject(&:completed?)
    @completed = @goals.select(&:completed?)
  end

  def show

  end

  def create
    @goal = @user.goals.new(goal_params)

    if @goal.save
      redirect_to user_goal_url(@user, @goal)
    else
      flash.now[:errors] = @goal.errors.full_messages
      render :new
    end
  end

  def update
    if @goal.update(goal_params)
      redirect_to user_goal_url(@user, @goal)
    else
      flash.now[:errors] = @goal.errors.full_messages
      render :edit
    end
  end

  def edit

  end

  def destroy
    @goal.delete
    redirect_to user_goals_url(@user)
  end

  private

  def set_user
    @user = User.find(params[:user_id])
  end

  def set_goal
    @goal = Goal.find(params[:id])
    redirect_to user_goals_url(@user) unless @goal
  end

  def goal_params
    params.require(:goal).permit(:title, :description, :completed)
  end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.find_by_credentials(user_params)
    if @user
      login!(@user)
      redirect_to user_url(@user)
    else
      @user = User.new(user_params)
      flash.now[:errors] = ["Username and/or password is incorrect!"]
      render :new
    end
  end

  def destroy
    logout!
    redirect_to root_url
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login!(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end


  private

  def user_params
    params.require(:user).permit(:username, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def current_user
    token = session[:session_token]
    return nil if token.nil?
    @current_user ||= User.find_by(session_token: token)
  end

  def current_user=(user)
    session[:session_token] = user.reset_session_token
    @current_user = user
  end

  def logged_in?
    !!current_user
  end

  def login!(user)
    self.current_user = user
  end

  def logout!
    current_user.session_token = nil
    @current_user = nil
    session[:session_token] = nil
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<p>Posted by <%= comment.user %> at <%= comment.created_at %></p>
<p><%= comment.body %></p>
<% object_user = object.class == User ? object : object.user %>
<% if object_user == current_user || comment.user == current_user %>
<%= button_to "Remove Comment", comment_url(comment), method: :delete %>
<% end %>

app/views/comments/_form.html.erb
<form action="<%= comments_url %>" method="post" accept-charset="utf-8">
  <%= form_auth_html %>
  <input type="hidden" name="comment[commentable_id]" value="<%= object.id %>">
  <input type="hidden" name="comment[commentable_type]" value="<%= object.class.to_s %>">

  <p><label for="comment">Comment</label></p>
  <textarea name="comment[body]" rows="8" cols="40" id="comment"><%= comment.body %></textarea>

  <p><input type="submit" value="Add Comment"></p>
</form>

app/views/goals/_complete_form.html.erb
<form action="<%= user_goal_url(user, goal) %>" method="post" accept-charset="utf-8">
  <%= form_auth_html %>
  <%= update_method_html %>
  <input type="hidden" name="goal[completed]" value="true">

  <p><input type="submit" value="Complete"></p>
</form>

app/views/goals/_form.html.erb
<!-- vars: new_goal boolean, @goal, @user -->
<form action="<%= new_goal ? user_goals_url(user) : user_goal_url(user, goal) %>"
   method="post" accept-charset="utf-8">
  <%= form_auth_html %>
  <%= update_method_html unless new_goal %>

  <table border="0" cellspacing="5" cellpadding="5">
    <tr>
      <td><label for="title">Title</label></td>
      <td><input type="text" name="goal[title]" value="<%= goal %>" id="title"></td>
    </tr>
  </table>

  <p><label for="description">Description</label></p>
  <textarea name="goal[description]" rows="8" cols="40" id="description"><%= goal.description %></textarea>

  <p><input type="submit" value="<%= new_goal ? "Create New Goal" : "Update Goal" %>"></p>
</form>

app/views/goals/_goal.html.erb
<h3><%= link_to goal.to_s, user_goal_url(goal.user, goal) %></h3>
<!-- button to completed? -->
<% unless goal.completed? %>
  <%= render partial: 'goals/complete_form', locals: { user: goal.user, goal: goal } %>
<% end %>

app/views/goals/edit.html.erb
<h1 id="edit_goal">Edit Goal: <%= @goal %></h1>
<%= render partial: 'form', locals: { goal: @goal, user: @user, new_goal: false } %>

app/views/goals/index.html.erb
<h1 id="user_goals"><%= @user.to_s.capitalize %>'s Goals</h1>

<h2>Pending Goals:</h2>

<% unless @uncompleted.empty? %>
  <% @uncompleted.each do |goal| %>
    <%= render partial: 'goal', locals: { goal: goal } %>
  <% end %>
<% end %>

<hr>

<h2>Completed Goals:</h2>
<% if @completed %>
  <% @completed.each do |goal| %>
    <%= render partial: 'goal', locals: { goal: goal } %>
  <% end %>
<% end %>

<% if current_user == @user %>
  <hr>
  <h2>Create a New Goal</h2>
  <%= render partial: 'form', locals: { goal: Goal.new, user: current_user, new_goal: true } %>
<% end %>

app/views/goals/new.html.erb
<h1 id="new_goal">New Goal</h1>
<%= render partial: 'form', locals: { goal: @goal, user: @user, new_goal: true } %>

app/views/goals/show.html.erb
<h1 id="goal_title"><%= @goal %></h1>
<p><%= @goal.description %></p>
<p style='color: red;'><%= @goal.completed? ? "Completed" : "Not Completed" %></p>
<!-- button to mark goal as completed -->
<p><%= link_to "Edit Goal", edit_user_goal_url(@user, @goal) %></p>
<%= button_to "Delete Goal", user_goal_url(@user, @goal), method: :delete %>

<h3>Comments</h3>
<% @goal.comments.each do |comment| %>
  <%= render partial: 'comments/comment', locals: { comment: comment, object: @goal, current_user: current_user } %>
<% end %>
<hr>
<h3>Add a Comment</h3>
<%= render partial: 'comments/form', locals: { comment: Comment.new, object: @goal } %>

<p><%= link_to "Back to #{@goal.user}", user_url(@goal.user) %></p>

app/views/layouts/_user_menu.html.erb
<div id="user_menu">
  <% if logged_in? %>
    <span>Welcome, <%= current_user.username %>!</span>
    <%= button_to 'Sign Out', session_url, method: :delete %>
  <% else %>
    <%= link_to "Sign In", new_session_url %>
    |
    <%= link_to "Sign Up", new_user_url %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GoalSetterApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


<%= render partial: 'layouts/user_menu' %>
<%= render partial: 'layouts/errors' %>

<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<form action="<%= new_user ? users_url : session_url %>" method="post" accept-charset="utf-8">
  <%= form_auth_html %>
  <table border="0" cellspacing="5" cellpadding="5">
    <tr>
      <td><label for="username">Username</label></td>
      <td><input type="text" name="user[username]" value="<%= user.username %>" id="username"></td>
    </tr>
    <tr>
      <td><label for="password">Password</label></td>
      <td><input type="password" name="user[password]" value="" id="password"></td>
    </tr>
  </table>

  <p><input type="submit" value="<%= new_user ? "Create User" : "Sign In" %>"></p>
</form>

app/views/users/new.html.erb
<h1 id="sign_up">Sign Up</h1>

<%= render partial: 'users/form', locals: { user: @user, new_user: true } %>

app/views/users/show.html.erb
<h1 id="username">Hi, <%= @user.username %>!</h1>

<h3><%= link_to "#{@user.to_s.capitalize}'s Goals", user_goals_url(@user) %></h3>

<h3>Comments</h3>
<% @user.comments.each do |comment| %>
  <%= render partial: 'comments/comment', locals: { comment: comment, object: @user, current_user: current_user } %>
<% end %>
<hr>
<h3>Add a Comment</h3>
<%= render partial: 'comments/form', locals: { comment: Comment.new, object: @user } %>